name: Exadel CompreFace
version: 1.2.0
url: https://github.com/exadel-inc/CompreFace
slug: compreface
description: Exadel CompreFace is a leading free and open-source face recognition system
full_access: false
ingress: false
arch:
  - amd64
startup: application
boot: auto
ports:
  80/tcp: 8000
ports_description:
  80/tcp: UI/API
options:
  POSTGRES_URL: jdbc:postgresql://localhost:5432/frs
  POSTGRES_USER: compreface
  POSTGRES_PASSWORD: M7yfTsBscdqvZs49
  POSTGRES_DB: frs
  API_JAVA_OPTS: "-Xmx1g"
schema:
  POSTGRES_URL: str
  POSTGRES_USER: str
  POSTGRES_PASSWORD: str
  POSTGRES_DB: str
  API_JAVA_OPTS: str
